CREATE DATABASE IF NOT EXISTS geometryjump CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE geometryjump;
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  created_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS levels (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NULL,
  name VARCHAR(100) NOT NULL,
  author VARCHAR(100) NOT NULL,
  json LONGTEXT NOT NULL,
  created_at DATETIME NOT NULL,
  INDEX (user_id),
  INDEX (name),
  INDEX (author)
);
